+++
index = '-KkEF-UUBEr5lisUg-m2'
name = 'Against Dilbert'
type = 'Column'
url = ""
shareimage = ""
twitterauto = 'Tell the Seattle Times how you feel about their decision to run climate change denialist propaganda.'
facebookauto = 'Tell the Seattle Times how you feel about their decision to run climate change denialist propaganda.'
make_image_tweet = False
byline = ['writers -JnJ-HhhwoaESh_YRgtB']
tags_notes = ['tags -KK7AuQuy1oP7gE1XntZ']
authors_notes = ""
books = ""
+++
We've known for years that *Dilbert* cartoonist Scott Adams is a dipshit men's rights activist. He compares [women who want equal pay to children](http://comicsalliance.com/scott-adam-sexist-mens-rights/). He's said [awful things about consent](https://www.themarysue.com/scott-adams-consent/). He endorsed Donald Trump and praised his "[clown genius](http://blog.dilbert.com/post/126589300371/clown-genius)" for a year before the election.

Adams may be a jackass, but he is not, strictly speaking, an idiot. He's kept his politics out of his comic strip, because he understands that people like *Dilbert* for its inane "boy-oh-boy-bosses-sure-do-suck-am-I-right?" gloss on office politics. If he were to start bleating his politics in his strip, people might start noticing *Dilbert* for the first time in years. And when people notice a comic strip, that's usually bad news for cartoonists. Comic strips have coasted along in the same haze of mediocrity for decades now. But newspapers are always looking for ways to cut costs nowaday â€” I'm sure some editors would love to cut a suddenly controversial strip from their pages if it meant they could save a little cash.

To my knowledge, this Sunday's *Dilbert* was the first time that Adams's politics overtly bled over onto the comics pages. [P.Z. Myers at Pharyngula](http://freethoughtblogs.com/pharyngula/2017/05/14/scott-adams-embarks-on-the-johnny-hart-road/) explains the politics behind the strip, which lands squarely on the side of climate change denial. 

This strip [did run in the *Seattle Times* on Sunday](http://www.seattletimes.com/comics-universal/?amu=/dilbert/2017/05/14). If you're a *Seattle Times* subscriber, you might want to [let the paper know](http://www.seattletimes.com/contact/) how you feel about Adams's garbage pseudo-science on the comics page.